project:
  type: book
  output-dir: _book

number-sections: true
#bibliography: references.bib

book:
  title: "INIKA_OH_TZ: WP4. Data Analysis"
  date: "`r format(Sys.time(), '%d %B, %Y')`"
  author: "Eve Zeyl Fiskebeck"
  chapters:
    - index.qmd
    - abstract.qmd
    - introduction.qmd
    - methods.qmd
    - results.qmd
    - discussion.qmd
    - conclusions.qmd  
    - references.qmd

# Not sure if this is necessary
# knit: (function(inputFile, encoding) {
#   rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../docs") })
  
format:
  html:
    theme: superhero
    #theme: darkly
    #theme: slate
    #css: styles.css
    toc: true
    toc_depth: 4
    toc_expand: 4
    toc-title: "Table of Contents"
    code-links: 
      - text: Source Code
        icon: githbub
        #href: data-import.py
  pdf:
    documentclass: scrreprt

editor: visual

