# Preface {.unnumbered}

<!-- This is index / preface of book 
This is a Quarto book.
To learn more about Quarto books visit <https://quarto.org/docs/books>.
Book structure explained here : https://quarto.org/docs/books/book-structure.html

-->

Note: 
Cover picture. Generated by Gemini [Large language model]. Google. (2024); the 26 Februar 2025.

## What you should learn during this course (aim)


## Plan course
TBA Camilla, Jannice and Madelaine

- `index.qmd` : this file


### Part: "Data analysis with R" 

- `data_analysis/data_analysis_resources.qmd`
  - additional ressources (incl. link previous course and previous ressources) for this course. More based on data analysis
   
- `data_analysis/data_wrangling.qmd`
  code for what needs to be done (can be extended) - data set checks reminders & joining data 

- `data_analysis/data_analysis.qmd` 
  code for what needs to be done (can be extended) 
   
   
### Part: "Bioinformatics. Comparative genomics" 

- `bioinformatics/bioinformatics_resources.qmd`
  - [ ] Galaxy ressources - Africa - Contact - application
  - [ ] Galaxy europe / our server 
  
- `bioinformatics/comparative_genomics.qmd`
  - [ ] sequence data reads ...
  
### Eventually 
- `references.qmd` (literature ressources and reads)
    
