---
title: "`r params$title`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: Eve Zeyl Fiskebeck and Madelaine Norström
params:
  title: "Training program: What you will be learning" 
  project_path: "`r here::here()`"

  
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../docs") })
  
output: 
  
  rmdformats::readthedown:
      css: style.css
      self_contained: true
      code_download: true
      toc_depth: 4
      df_print: paged
      code_folding: hide
      author: params$author
      highlight: espresso
      number_sections: true
      

  
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, 
                      message=FALSE, warning=FALSE,
                      results = 'hide')
```

> Program to run by Madelaine about training order and content Trying to
> reduce the load - brain ...and have a way to come back for repeats day
> after example whonet test data

# Before we come: Setup (chap 0)

At arrival :

-   [ ]  Control before starting the data course
-   [ ]  **Rscript to run to install packages ? or Renv ?** Need to do one and try - this could help - This MUST be done at the end of the course preparation, however to be sure we have all ? ( We all have installed the needed packages and Programs?)


# Introduction (chap 1)

-   [ ]  Goal of the course
-   [ ]  what to expect and state of mind
-   [ ]  what about using AI to write code ?
-   [ ]  additional resources you can use to learn more, here and
    through the course

# Basic R and github with Rstudio (chap 2)
 
 > learning how to use a R markdown document and git backup, small intro to R programming language

Starting point: `learning_R` git repo has been cloned locally

-   [ ]   Rstudio usage: creating / opening an Rproject
-   [ ]   Git software is used for backup of notes and code versioning via Rstudio. (Workflow)
-   [ ]   .gitignore file exercise (setup at the same time)
-   [ ]   Using a notebook in Rstudio: anatomy, text, code and rendering
-   [ ]   Exercise Using a R markdown document & Fast overview of R programming language (introduction terms and running things in the cells) ! THIS NEED TO BE EXPLAINED DURING THE COURSE 

We have during the course here : 

-   [ ]  installation packages and loading them
-   [ ]  taking notes in Rmarkdown and runnign cells
-   [ ]  R notions ...about R objects (not in depth)
    -   [ ]  some common data types
    -   [ ]  introduction to use help
    -   [ ]  small intro to functions
    -   [ ]  sub-setting / indexes
    -   [ ]  a bit of view of objects
    -   [ ]  notions in R - different ways to do things (no perfect code!)
    -   [ ]  pipes 
    -   [ ]  some tricks 
-   [ ]  Saving your code and notes to git and push to github.
    -   [ ]  Using git in R to backup your code in github (add - commit - push)
  
-   [ ]   Exercise : Printing your code in a word document


# Basic R for data analysis (chap 3)

NB: Data from Human sampling (KoboToolbox)

-   [ ]  A good organisation of your project for data analysis

-   [ ]  First steps in data analysis
    -   [ ]  Reading a data frame
    -   [ ]  checking and setting correct data types
    -   [ ]  data types (review, and add)
    -   [ ]  Obtaining a fast overview of the data contained in a data frame (Explain what is a data frame)
    -   [ ]  Object Visualization (code and Rstudio environment)
    -   [ ]  Getting a fast summary of the data contained in your data frame
        -   [ ]  counts (col, row)
        -   [ ]  factors and levels (summary table / tally)
        -   [ ]  using pipes

-   [ ]   Data frame manipulation with dplyr (etc...)
    -   [ ]  cleaning column names ( values - eg. NA and spaces, special characters)
    -   [ ]  selecting columns
    -   [ ]  mutating
    -   [ ]  filtering
    -   [ ]  finding specific columns
    -   [ ]  arranging rows by values in the columns  
    -   [ ]  saving into a spreadsheet 
    -   [ ]  summary (base::)
    -   [ ]  checking if values are unique (ID)
    -   [ ]  group_by
    -   [ ]  count and creation of simple contingency tables
    -   [ ]  filtering out rows with poor data quality (using filter on ID) 
    -   [ ]  exporting dataset to file (csv)
    -   [ ]  if_else and case_when to replace missing values
    -   [ ]  count and summary functions (contingency tables) in dplyr
    -   [ ]  some basic plotting
    -   [ ]  exporting/reading object to/from rds file

Exercises to go further (we do not need to do all). 
Solutions are patterns the students can reuse when working with their own data.   
    
All in the spirit of data inspection to ensure proper quality: Which includes 
detecting mistakes or inconsistencies. 
Learning why its important not to modify the 
raw data, doing so by code allows to detect errors and allows transparency
of our choices. 
    

# Using data directly from a database (WHONET) and joining datasets. (chap 4)


NB: WHONET "fake" data for learning + data from Human sampling (KoboToolbox)

-   [ ]  creating a connection to a SQLite database
    -   [ ]  why to use a database
    -   [ ]  lazy evaluation (notion)
    
-   [ ]  querying a table in a database using dbplyr
    -   [ ]  evaluating the query (collect) 

-   [ ]  Reminder - reading from rds file    
-   [ ]  joining data frames (WHONET to human data questionnaires)
-   [ ]  making categories and plotting them 
-   [ ]  data wide and long format trick
-   [ ]  "bad looking plot", box plots, simple heat map
-   [ ]  saving plots 

<u>Only if time permits:</u>

-   [ ]  removing objects from memory (dput trick)
-   [ ]  notion of identity in objects and memory pointers - awareness identical and == 
 -   [ ]  some more exercises and tidy selection means
  


<!-- I  think it will be actually more than enough material 

## Eventually

-   pulling from github - recovery of what has been done and
    collaboration
-   github and Zenodo - can show them article
-   writing functions using dplyr / tidyverse ... oops

? - decimals ... warning ! not done -\> do that during transformation -
--> 

Back to [Index](index.html)