
Manage_Healthy_Chicken_Cleaning_OR_DIsinfect ="What do you do to keep your chicken healthy, so they don't get sick? (don't read options)/Clean or disinfect" ,                                                                                 
Manage_Healthy_Chicken_Vaccine_Drugs= "What do you do to keep your chicken healthy, so they don't get sick? (don't read options)/Use vet drugs (eg.vaccine)" ,                                                                         
Manage_Healthy_Chicken_Well_Fed= "What do you do to keep your chicken healthy, so they don't get sick? (don't read options)/Keep well fed"  ,                                                                                     
Manage_Healthy_Chicken_Spec_Fed = "What do you do to keep your chicken healthy, so they don't get sick? (don't read options)/Giving special feed",                                                                                 
Manage_Healthy_Chicken_Fencing= "What do you do to keep your chicken healthy, so they don't get sick? (don't read options)/Fencing"    ,                                                                                         
Manage_Healthy_Chicken_Others =  "What do you do to keep your chicken healthy, so they don't get sick? (don't read options)/Other specify", 



Disease_management="What did you do when your chicken was sick? (several options)",                                                                                                                      
Disease_management_Traditional= "What did you do when your chicken was sick? (several options)/Use traditional medicine"                  ,                                                                                      
Disease_management_Medicine_Drigstore="What did you do when your chicken was sick? (several options)/Use medicine from veterinary drug store"    ,                                                                                     
Disease_management_Consult_animal_health= "What did you do when your chicken was sick? (several options)/Consult Community animal health worker"      ,                                                                                    
Disease_management_Consult_private_Veterinarian= "What did you do when your chicken was sick? (several options)/Consult a private veterinarian"               ,                                                                                   
Disease_management_Others= "What did you do when your chicken was sick? (several options)/Other specify.."                               ,                                                                                  
Disease_management_Specification = "If others, specify...139",

                                                           

Source_OF_OBTAIN_ABs= "Where do you obtain antibiotics?"  , 
Source_OF_OBTAIN_ABs_Formal_Vet="Where do you obtain antibiotics?/option_1__formal_veterinary_channels__e_"                                                          ,                                                           
Source_OF_OBTAIN_ABs_informal_local ="Where do you obtain antibiotics?/option_2__informal_sources__e_g__local_m"                                                           ,                                                          
Source_OF_OBTAIN_ABs_Formal_Vet_2 = "Where do you obtain antibiotics?/Formal veterinary channels (e.g., veterinarians, pharmacies)" ,                                                         
Source_OF_OBTAIN_ABs_informal_local_2 = "Where do you obtain antibiotics?/Informal sources (e.g., local markets, unauthorized vendors)"                                         ,  

Jugde_AB_Treatment="Who judges the necessity of an antibiotic treatment in your farm? (You may select more than one option)"                                ,                                                       
Jugde_AB_Treatment_Vet= "Who judges the necessity of an antibiotic treatment in your farm? (You may select more than one option)/Veterinarian"                    ,                                                      
Jugde_AB_Treatment_ParaVet ="Who judges the necessity of an antibiotic treatment in your farm? (You may select more than one option)/Para veterinarian"                ,                                                     
Jugde_AB_Treatment_Drug_vendor=   "Who judges the necessity of an antibiotic treatment in your farm? (You may select more than one option)/Drug vendors"                      ,                                                    
Jugde_AB_Treatment_Owner=  "Who judges the necessity of an antibiotic treatment in your farm? (You may select more than one option)/Owner"                              ,                                                   
Jugde_AB_Treatment_Others=  "Who judges the necessity of an antibiotic treatment in your farm? (You may select more than one option)/Other"                               ,                                                  
Jugde_AB_Treatment_Specification =  "if others, please specify" ,                                                                                                                                                                    

Means_of_Decion_ABUSAGE= "How does he/she reach at the judgment of advising you to use antibiotics on your farm"                                                        ,                                                 
Means_of_Decion_ABUSAGE_FARMVISIT ="How does he/she reach at the judgment of advising you to use antibiotics on your farm/option_1__visiting_the_farm"                             ,                                                
Means_of_Decion_ABUSAGE_EXPLAIN_CLINICAL="How does he/she reach at the judgment of advising you to use antibiotics on your farm/option_2__explaining_the_clinical_signs_"                 ,                                               
Means_of_Decion_ABUSAGE_PREVIOUS_EXP= "How does he/she reach at the judgment of advising you to use antibiotics on your farm/option_3__basing_on_previous_visit_exper"                  ,                                              
Means_of_Decion_ABUSAGE_PHOTO ="How does he/she reach at the judgment of advising you to use antibiotics on your farm/option_4__sending_a_photo_of_dead_and_bi"                   ,                                             
Means_of_Decion_ABUSAGE_FARMVISIT_2 ="How does he/she reach at the judgment of advising you to use antibiotics on your farm/Visiting the farm"                                           ,                                            
Means_of_Decion_ABUSAGE_EXPLAIN_CLINICAL_2 ="How does he/she reach at the judgment of advising you to use antibiotics on your farm/Explaining the clinical signs to him/her"                     ,                                           
Means_of_Decion_ABUSAGE_PREVIOUS_EXP_2= "How does he/she reach at the judgment of advising you to use antibiotics on your farm/Basing on previous visit experience"                           ,                                          
Means_of_Decion_ABUSAGE_PHOTO_2 ="How does he/she reach at the judgment of advising you to use antibiotics on your farm/Sending a photo of dead and birds showing clinical signs"       ,                                         


PLACE_OF_AB_PURHASE= "Where do you purchase your drugs?"                                                                                                                     ,                                        
PLACE_OF_AB_PURHASE_VETPHARMACY= "Where do you purchase your drugs?/Veterinary pharmacy"                                                                                                  ,                                       
PLACE_OF_AB_PURHASE_VILLAGE_PHARMACY= "Where do you purchase your drugs?/small village pharmacy"                                                                                                ,                                      
PLACE_OF_AB_PURHASE_LOCAL_MARKET= "Where do you purchase your drugs?/Local market"                                                                                                           ,                                     
PLACE_OF_AB_PURHASE_FARMER_COLLEGES= "Where do you purchase your drugs?/Farmer colleague"                                                                                                        ,                                    
PLACE_OF_AB_PURHASE_OTHER= "Where do you purchase your drugs?/Other"                                                                                                                    ,                                   
PLACE_OF_AB_PURHASE_SPECIFICATION = "If others, please specify...188"                                                                                                                             ,

Follow_Dosage_AB= "Do you typically follow recommended dosage when using antibiotics?"                                                                                           ,
Records_AB= "Do you keep records of antibiotics administered?"                                                                                                              ,                                
Follow_Withdrawal_AB  =   "Do you typically follow recommended withdrawal periods when using antibiotics?"                                                                                 ,                               
Follow_Withdrawal_AB_Other_Farmers  =  "Do you think broiler farmers in general follow recommended dosages and withdrawal periods when using antibiotics?"                                               ,                              
Alternative_TO_ABUSAGE= "Are there any other alternatives apart from the use of antibiotics?"                                                                                              ,                             
ALternatives_AB_Description="If yes what would they be?"                                                                                                                                        , 


Barriers_To_Adopt_AB_Alternatives ="What barriers do you face in adopting alternative practices that reduce the need for antibiotic use? (Select all that apply)"                                       ,
Barriers_To_Adopt_AB_Alternatives_Knowledge_Alternative = "What barriers do you face in adopting alternative practices that reduce the need for antibiotic use? (Select all that apply)/Lack of knowledge about alternative practices" ,                   
Barriers_To_Adopt_AB_Alternatives_resources_Alternative ="What barriers do you face in adopting alternative practices that reduce the need for antibiotic use? (Select all that apply)/Limited access to resources for alternative practices"  ,          
Barriers_To_Adopt_AB_Alternatives_traditionalpractices = "What barriers do you face in adopting alternative practices that reduce the need for antibiotic use? (Select all that apply)/Cultural or traditional practices"                       ,         
Barriers_To_Adopt_AB_Alternatives_Economic="What barriers do you face in adopting alternative practices that reduce the need for antibiotic use? (Select all that apply)/Economic constraints"                                        ,     
Barriers_To_Adopt_AB_Alternatives_Other="What barriers do you face in adopting alternative practices that reduce the need for antibiotic use? (Select all that apply)/Other (please specify)"                                       ,    
Barriers_To_Adopt_AB_Alternatives_Specification= "If others, please specify...201"                                                                                                                                                            ,

INFLUENCE_CHOICE_OF_AB="What influences your choice of antibiotics to use? more than one response is allowed"                                                                                                        , 
INFLUENCE_CHOICE_OF_AB_PRICE= "What influences your choice of antibiotics to use? more than one response is allowed/option_1__price"                                                                                         , 
INFLUENCE_CHOICE_OF_AB_AVALIABILITY="What influences your choice of antibiotics to use? more than one response is allowed/option_2__availability"                                                                                   ,
INFLUENCE_CHOICE_OF_AB_EFFICIENCY= "What influences your choice of antibiotics to use? more than one response is allowed/option_3__efficiency"                                                                                     ,
INFLUENCE_CHOICE_OF_AB_PRESCRIPTION= "What influences your choice of antibiotics to use? more than one response is allowed/option_4__prescription_by_the_veterinari"                                                                 ,
INFLUENCE_CHOICE_OF_AB_PRESCR_LOCAL_MARKET_VENDOR ="What influences your choice of antibiotics to use? more than one response is allowed/option_5__prescription_by_the_local_mark"                                                                 ,
INFLUENCE_CHOICE_OF_AB_2= "What influences your choice of antibiotics to use? more than one response is allowed/option_6__prescription_by_the_provender_", 
INFLUENCE_CHOICE_OF_AB_PRICE_2= "What influences your choice of antibiotics to use? more than one response is allowed/Price"                                                                                                    ,
INFLUENCE_CHOICE_OF_AB_AVALIABILITY_2= "What influences your choice of antibiotics to use? more than one response is allowed/Availability"                                                                                             ,
INFLUENCE_CHOICE_OF_AB_EFFICIENCY_2= "What influences your choice of antibiotics to use? more than one response is allowed/Efficiency"                                                                                               ,
INFLUENCE_CHOICE_OF_AB_PRESCRIPTION_2=  "What influences your choice of antibiotics to use? more than one response is allowed/Prescription by the veterinarian"                                                                         ,
INFLUENCE_CHOICE_OF_AB_PRESCR_LOCAL_MARKET_VENDOR_2 ="What influences your choice of antibiotics to use? more than one response is allowed/Prescription by the local market vendor"                                                                  ,
INFLUENCE_CHOICE_OF_AB_PRESCR_Provender_Seller =    "What influences your choice of antibiotics to use? more than one response is allowed/Prescription by the provender seller"                                                                     ,

AB_Status_Now= "Are your chickens under antibiotic treatment now?"                                                                                                                                             ,
Determine_Dose_AB= "How do you determine the dose/quantity of the antibiotic? (can provide more than one answer)"                                                                                                  ,
Determine_Dose_AB_Animal_Health_P= "How do you determine the dose/quantity of the antibiotic? (can provide more than one answer)/option_1__according_to_animal_health_pra"                                                         ,
Determine_Dose_AB_Manufacturer=     "How do you determine the dose/quantity of the antibiotic? (can provide more than one answer)/option_2__according_to_manufacturers__in"                                                         ,
Determine_Dose_AB_Weighing=      "How do you determine the dose/quantity of the antibiotic? (can provide more than one answer)/option_3__by_weighing_the_birds"                                                                  ,
Determine_Dose_AB_Estimate_Weight=  "How do you determine the dose/quantity of the antibiotic? (can provide more than one answer)/option_4__by_estimating_the_weight_of_th"                                                         ,
Determine_Dose_AB_Age=   "How do you determine the dose/quantity of the antibiotic? (can provide more than one answer)/option_5__according_to_their_age"                                                                 ,
Determine_Dose_AB_DONTKNOW= "How do you determine the dose/quantity of the antibiotic? (can provide more than one answer)/option_6__don_t_know"                                                                             ,
Determine_Dose_AB_OTHERSSPEC=    "How do you determine the dose/quantity of the antibiotic? (can provide more than one answer)/option_7__others_specify",
Determine_Dose_AB_Animal_Health_P_2="How do you determine the dose/quantity of the antibiotic? (can provide more than one answer)/According to animal health practitioners instructions"                                            ,
Determine_Dose_AB_Manufacturer_2=   "How do you determine the dose/quantity of the antibiotic? (can provide more than one answer)/According to manufacturers' instructions"                                                         ,
Determine_Dose_AB_Weighing_2=  "How do you determine the dose/quantity of the antibiotic? (can provide more than one answer)/By weighing the birds"                                                                            ,
Determine_Dose_AB_Estimate_Weight_2=  "How do you determine the dose/quantity of the antibiotic? (can provide more than one answer)/By estimating the weight of the birds"                                                            ,
Determine_Dose_AB_Age_2=  "How do you determine the dose/quantity of the antibiotic? (can provide more than one answer)/According to their age"                                                                           ,
Determine_Dose_AB_DONTKNOW_2=  "How do you determine the dose/quantity of the antibiotic? (can provide more than one answer)/Don't know"                                                                                       ,
Determine_Dose_AB_OTHERSSPEC_2=    "How do you determine the dose/quantity of the antibiotic? (can provide more than one answer)/Others specify"                                                                                   ,

Treatment_Failure_Repeat_Same= "In case of treatment failure, do you repeat the same treatment?"                                                                                                                               ,
Treatment_Failure_Options= "In case of persistence of symptoms after first treatment, what do you do?( you select more than one option)"                                                                                   ,
Treatment_Failure_Option_Increase_Dose= "In case of persistence of symptoms after first treatment, what do you do?( you select more than one option)/Increase the dosage of the same treatment"                                         ,
Treatment_Failure_Options_Increase_Duration=  "In case of persistence of symptoms after first treatment, what do you do?( you select more than one option)/Increase the duration of the same treatment"                                       ,
Treatment_Failure_Options_Change_Drug=   "In case of persistence of symptoms after first treatment, what do you do?( you select more than one option)/Change the drug"                                                                   ,
Treatment_Failure_Options_Mixture_Drugs=  "In case of persistence of symptoms after first treatment, what do you do?( you select more than one option)/Prescribe a mixture of drugs"                                                      ,
Treatment_Failure_Options_Sell_ASAP="In case of persistence of symptoms after first treatment, what do you do?( you select more than one option)/Commercialization ( Sell the chicken as quickly as possible before more are dying)",
Treatment_Failure_Options_Inditgenous_Treat="In case of persistence of symptoms after first treatment, what do you do?( you select more than one option)/Indigenous treatment"                                                              ,
Treatment_Failure_Options_Others= "In case of persistence of symptoms after first treatment, what do you do?( you select more than one option)/Others (specify)" ,
Treatment_Failure_Options_Specification= "If others, please specify...240"                                                                                                          ,

Frequenc_Same_Treatment_BeforeChange="How many times do you apply the same treatment before changing for a possible alternative?"                                                                                                    ,
Respect_the_Treatment_Guidelines_by_AHP="Do you respect/align with the treatment guidelines prescribed by the Animal health practitioners?"                                                                                             ,
Respect_Withdrawal= "Do you consider and adhere to the withdraw period?"                                                                                                                                            ,
Barriers_Withdrawal= "If No, why is it difficult to consider/apply the withdraw period?"                                                                                                                             ,
Mix_ABS_EFFECIVENESS= "Do you combine several antibiotics to increase efficiency?"                                                                                                                                    ,

Management_DEADBIRDS="What do you do with the dead chickens ?"                                                                                                                                                       ,
Management_DEADBIRDS_Incinerate= "What do you do with the dead chickens ?/Incinerate"                                                                                                                                            ,
Management_DEADBIRDS_IN_PIT= "What do you do with the dead chickens ?/Throw in the pit"                                                                                                                                      ,
Management_DEADBIRDS_Dustbin= "What do you do with the dead chickens ?/Throw in the dustbin"                                                                                                                                  ,
Management_DEADBIRDS_Consume= "What do you do with the dead chickens ?/Consume"                                                                                                                                               ,
Management_DEADBIRDS_Domesticated_ANIMALS= "What do you do with the dead chickens ?/Give to other domesticated animals"                                                                                                                    ,
Management_DEADBIRDS_Other= "What do you do with the dead chickens ?/Other specify"                                                                                                                                         ,
Management_DEADBIRDS_Specification= "If others, please specify...253"                                                                                                                                                               ,

Selling_DURING_TREATEMENT="During the treatment period, do you continue selling chickens?"                                                                                                                                ,
Selling_DURING_TREATEMENT_OTHERFARMERS= "In general, do broiler farmers continue selling the chickens during the treatment period?"                                                                                                     ,

Treatment_Failure_BIRDS= "When the treatment is not working, what do you do with the chickens?"                                                                                                                          ,
Treatment_Failure_BIRD_SaleS= "When the treatment is not working, what do you do with the chickens?/Sale"                                                                                                                     ,
Treatment_Failure_BIRDS_Slaughter= "When the treatment is not working, what do you do with the chickens?/Slaughter"                                                                                                                ,
Treatment_Failure_BIRDS_Other= "When the treatment is not working, what do you do with the chickens?/Other (Specify)"                                                                                                          ,
Treatment_Failure_BIRDS_Specification=   "If others, please specify...260"                                                                                                                                                               ,

Expired_Drugs= "What do you do with expired drugs?"                                                                                                                                                            ,
Expired_Drugs_Pharmacy=  "What do you do with expired drugs?/option_1__back_to_pharmacy"                                                                                                                                 ,
Expired_Drugs_Nature=  "What do you do with expired drugs?/option_2__thrown_in_nature"                                                                                                                                 ,
Expired_Drugs_Conserve=  "What do you do with expired drugs?/option_3__conserve"                                                                                                                                         ,
Expired_Drugs_Animals=  "What do you do with expired drugs?/option_4__administer_to_anima"                                                                                                                              ,
Expired_Drugs_Pharmacy_2= "What do you do with expired drugs?/Take back to pharmacy"                                                                                                                                      ,
Expired_Drugs_Nature_2=  "What do you do with expired drugs?/Thrown in nature"                                                                                                                                           ,
Expired_Drugs_Conserve_2=  "What do you do with expired drugs?/Conserve"                                                                                                                                                   ,
Expired_Drugs_Animals_2=   "What do you do with expired drugs?/Administer to animal",

AB_Information_access= "Do you feel that you have access to information about antibiotic resistance?"                                                                                                                  ,
ABUsage_Learning="Do you think you are willing to invest time and resources in learning about responsible antibiotic use practices?"                                                                             ,
ABUsage_Participation_AB=    "Would you be interested in participating in workshops or training sessions on sustainable anti practices, including antibiotic use?"                                                           ,

Support= "Have you received any support from? (can select multiple)"                                                                                                                                     ,
Support_Family="Have you received any support from? (can select multiple)/Close family"                                                                                                                        ,
Support_Relatives=  "Have you received any support from? (can select multiple)/Relatives"                                                                                                                           ,
Support_Friends=  "Have you received any support from? (can select multiple)/Friends"                                                                                                                             ,
Support_Neighbors=  "Have you received any support from? (can select multiple)/Neighbors"                                                                                                                           ,
Support_NCANGO =  "Have you received any support from? (can select multiple)/NCA/NGOs"                                                                                                                            ,
Support_Local=  "Have you received any support from? (can select multiple)/Local social/agricultural unions"                                                                                                    ,
Support_Government=  "Have you received any support from? (can select multiple)/Government"                                                                                                                          ,
Support_None=  "Have you received any support from? (can select multiple)/No support"                                                                                                                          ,

Rating_Support="How would you rate the importance of the support you received from each of the selected above?...282"                                                                                          ,

Source_AMR= "What are the main sources of your information regarding AMR? (can select multiple)"                                                                                                            ,
Source_AMR_Family=  "What are the main sources of your information regarding AMR? (can select multiple)/option_1__close_family"                                                                                     ,
Source_AMR_Relatives=  "What are the main sources of your information regarding AMR? (can select multiple)/option_2__relatives"                                                                                        ,
Source_AMR_Friends=  "What are the main sources of your information regarding AMR? (can select multiple)/option_3_friends"                                                                                           ,
Source_AMR_Neighbors=  "What are the main sources of your information regarding AMR? (can select multiple)/option_4__neighbors"                                                                                        ,
Source_AMR_Local_Agriculture=     "What are the main sources of your information regarding AMR? (can select multiple)/option_5__local_social_agricultural_asso"                                                                   ,
Source_AMR_LocalGov=       "What are the main sources of your information regarding AMR? (can select multiple)/option_6__local_government"                                                                                 ,
Source_AMR_NCA_NGOs=       "What are the main sources of your information regarding AMR? (can select multiple)/option_7__nca_ngos"                                                                                         ,
Source_AMR_Nation_Gov=    "What are the main sources of your information regarding AMR? (can select multiple)/option_8__national_government"                                                                              ,
Source_AMR_Media= "What are the main sources of your information regarding AMR? (can select multiple)/option_9__media"                                                                                            ,
Source_AMR_None=   "What are the main sources of your information regarding AMR? (can select multiple)/option_10__no_information"   ,

Source_AMR_Family_2=  "What are the main sources of your information regarding AMR? (can select multiple)/Close family"                                                                                               ,
Source_AMR_Relatives_2= "What are the main sources of your information regarding AMR? (can select multiple)/Relatives"                                                                                                  ,
Source_AMR_Friends_2= "What are the main sources of your information regarding AMR? (can select multiple)/Friends"                                                                                                    ,
Source_AMR_Neighbors_2= "What are the main sources of your information regarding AMR? (can select multiple)/Neighbors"                                                                                                  ,
Source_AMR_Local_Agriculture_2=  "What are the main sources of your information regarding AMR? (can select multiple)/Local social/agricultural associations"                                                                     ,
Source_AMR_LocalGov_2= "What are the main sources of your information regarding AMR? (can select multiple)/Local government"                                                                                           ,
Source_AMR_NCA_NGOs_2=  "What are the main sources of your information regarding AMR? (can select multiple)/NCA/NGOs"                                                                                                   ,
Source_AMR_Nation_Gov_2= "What are the main sources of your information regarding AMR? (can select multiple)/National government"                                                                                        ,
Source_AMR_Media_2=  "What are the main sources of your information regarding AMR? (can select multiple)/Media"                                                                                                      ,
Source_AMR_None_2=  "What are the main sources of your information regarding AMR? (can select multiple)/No information",

Rate_Support_2= "How would you rate the importance of the support you received from each of the selected above?...304"                                                                                          ,

Local_engagement_Community="Are you currently involved in a local community/association?"                                                                                                                                  ,
Freq_Participation= "How often do you participate?"                                                                                                                                                                 ,
Participation_Usefulnes= "Is it helpful for you to participate in those organizations?"                                                                                                                                  ,
Employment_Status= "What is your current employment status?"                                                                                                                                                       ,
Income_Source="What is your primary source of income?"  ,
Income_Source_other = "If others, please specify...310"                                                                                                                                                               ,
Income_Broiler_main = "Is broiler farming your main income?"                                                                                                                                                          ,
NOchicken_SoldPerMonth ="How many chickens do you approximately sell per month?"                                                                                                                                        ,
Credit_LOans = "Do you have access to credit or loans for your farming activities?"                                                                                                                            ,
DependFarmingINcome = "How many family members depend on your broiler farming income?"                                                                                                                                ,
Gender_roles_BroilerFarming = "In your own words, how do you perceive the roles of men and women in broiler farming and within the broader framework of AMU practices? Who is involved more?"                                 ,
Gender_roles_BroilerFarming_Own =   "Owning farms"                                                                                                                                                                                  ,
Gender_roles_BroilerFarming_Clean =   "Cleaning farmhouse/sheds."                                                                                                                                                                     ,
Gender_roles_BroilerFarming_Selling = "Selling the chickens"                                                                                                                                                                          ,
Gender_roles_BroilerFarming_Adm_AB ="Administering antibiotics"                                                                                                                                                                     ,
Gender_roles_BroilerFarming_Feeding = "Feeding chickens"                                                                                                                                                                              ,
Gender_roles_BroilerFarming_CARE =  "Taking care of the chickens"                                                                                                                                                                   ,
Gender_roles_BroilerFarming_Disp_Dead ="Disposal of dead broilers"                                                                                                                                                                     ,
Gender_roles_BroilerFarming_Disp_Manure =  "Disposal of manure/wastes"                                                                                                                                                                     ,
Gender_roles_BroilerFarming_TreatmentDecision ="Decision for treatment"                                                                                                                                                                        ,
Gender_roles_BroilerFarming_Water ="Providing water"                                                                                                                                                                               ,
Gender_roles_BroilerFarming_Disp_ABs = "Disposal of antibiotics left over"                                                                                                                                                             ,
Gender_roles_BroilerFarming_IncomeDec ="Decisions to use income from broilers"                                                                                                                                                         ,
Gender_Reasons = "In your opinion, what are the reasons for males/females being involved more in broiler farmers?"                                                                                               ,

Goverment_FocusAreas = "Which of the following issues do you think the Tanzanian government should focus on? (select a maximum of three)"                                                                             , 
Goverment_FocusAreas_ClimateChange = "Which of the following issues do you think the Tanzanian government should focus on? (select a maximum of three)/Tackling climate change"                                                      ,
Goverment_FocusAreas_Taxing_Multinationalcompanies = "Which of the following issues do you think the Tanzanian government should focus on? (select a maximum of three)/Taxing large multinational companies"                                         ,
Goverment_FocusAreas_Tackling_AMR = "Which of the following issues do you think the Tanzanian government should focus on? (select a maximum of three)/Tackling AMR"                                                                 ,
Goverment_FocusAreas_Reduce_Unemployment = "Which of the following issues do you think the Tanzanian government should focus on? (select a maximum of three)/Reducing unemployment"                                                        ,
Goverment_FocusArea_AgrigDevelopments = "Which of the following issues do you think the Tanzanian government should focus on? (select a maximum of three)/Investing in agricultural development"                                        ,
Goverment_FocusAreas_NextPandemic = "Which of the following issues do you think the Tanzanian government should focus on? (select a maximum of three)/Preparing for the next pandemic"                                              ,
Goverment_FocusAreas_Migration = "Which of the following issues do you think the Tanzanian government should focus on? (select a maximum of three)/Managing migration"                                                           ,
Goverment_FocusAreas_Protect_Refugees = "Which of the following issues do you think the Tanzanian government should focus on? (select a maximum of three)/Protecting refugees"                                                          ,
Goverment_FocusAreas_Reduce_Inequity = "Which of the following issues do you think the Tanzanian government should focus on? (select a maximum of three)/Reducing inequality and discrimination"                                       ,
Goverment_FocusAreas_Misinformation = "Which of the following issues do you think the Tanzanian government should focus on? (select a maximum of three)/Tackling fake news and misinformation"                                        ,
Goverment_FocusAreas_Crime =  "Which of the following issues do you think the Tanzanian government should focus on? (select a maximum of three)/Fighting crime and terrorism"                                                 ,
Goverment_FocusAreas_Other =  "Which of the following issues do you think the Tanzanian government should focus on? (select a maximum of three)/Other"                                                                        ,
Goverment_FocusAreas_Specification = "If others, please specify...358"                                                                                                                                                               ,
